spring:
  application:
    name: spk-seed
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USER}
    password: ${REDIS_PASS}
    timeout: ${REDIS_TIMEOUT}
