spring:
  application:
    name: spk-seed
  data:
    mongodb:
      uri: mongodb://redbee:r3db33@localhost:27017
      database: coupons
  redis:
    host: localhost
    port: 6379
    username: randomuser
    password: randompass
    timeout: 2s
