spring:
  application:
    name: spk-seed-evolution
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
    mssql:
      host: ${MSSQL_HOST}
      port: ${MSSQL_PORT}
      database: ${MSSQL_DATABASE}
      username: ${MSSQL_USER}
      password: ${MSSQL_PASS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USER}
    password: ${REDIS_PASS}
    timeout: ${REDIS_TIMEOUT}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SQLSERVER_SERVER_URL}
    username: ${SQLSERVER_USER}
    password: ${SQLSERVER_PASS}
