spring:
  application:
    name: spk-seed
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USER}
    password: ${REDIS_PASS}
    timeout: ${REDIS_TIMEOUT}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SQLSERVER_SERVER_URL}
    username: ${SQLSERVER_USER}
    password: ${SQLSERVER_PASS}
