environment: main
service_name: kotlin-gradle-template
namespace: idp

hpa:
  minReplicas: 1
  maxReplicas: 1

backend:
  image:
    repository: 682320626241.dkr.ecr.us-east-1.amazonaws.com/kotlin-gradle-template
    tag: "from_cd"
    pullPolicy: Always
  
  replicaCount: 1
  historyLimitReplicas: 0
  resources:
    requests:
      cpu: 100m
    limits:
      cpu: 250m

  service:
    name: backend
    data:
      type: Internal
      port: 8080
      protocol: TCP
      target_port: 8080
      name: http
