# docker-compose.yml - Only for local debug purposes

version: '3.8'

services:
  postgres:
    image: postgres
    container_name: loc-postgres
    logging:
      driver: none
    environment:
      TZ: UTC
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  mongo:
    image: mongo:latest
    container_name: loc-mongo
    logging:
      driver: none
    environment:
      TZ: UTC
    ports:
      - '27017:27017'

  redis:
    image: redis:3-alpine
    container_name: loc-redis
    logging:
      driver: none
    environment:
      TZ: UTC
    ports:
      - '6379:6379'

  zookeeper:
    container_name: loc-zookeeper
    logging:
      driver: none
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    container_name: loc-kafka
    image: wurstmeister/kafka:2.12-2.3.0
    logging:
      driver: none
    environment:
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka:19092,
        LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19092,
        LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "prisma.sampleApi.topic.v1:1:1"
      KAFKA_LOG4J_LOGGERS: >-
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
