apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    run: backend
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: {{ .Values.backend.historyLimitReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
        run: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          env:
            - name: CURRENT_COMMIT
              value: {{ .Values.backend.image.tag }}
          livenessProbe:
            httpGet:
              path: /domain/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /domain/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          #ports:
          #  - containerPort: {{ .Values.backend.service.data.target_port }}
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
